// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjAyCURbQ4eBlbKQeXMjAYBpKCNpNKG_Y',
    appId: '1:369044560836:web:6a8879026fb8bc567a2291',
    messagingSenderId: '369044560836',
    projectId: 'complete-e-commerce',
    authDomain: 'complete-e-commerce.firebaseapp.com',
    storageBucket: 'complete-e-commerce.appspot.com',
    measurementId: 'G-42RLG3HBT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7h6SKZV_zurmSDlIq7BYATdggCFXltfM',
    appId: '1:369044560836:android:c0c4c95e5aa7ac497a2291',
    messagingSenderId: '369044560836',
    projectId: 'complete-e-commerce',
    storageBucket: 'complete-e-commerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp5p6-bLErHScXLMCl2bmYQrxRq3ihdn4',
    appId: '1:369044560836:ios:87622413a71a2a9e7a2291',
    messagingSenderId: '369044560836',
    projectId: 'complete-e-commerce',
    storageBucket: 'complete-e-commerce.appspot.com',
    iosClientId: '369044560836-9dtoj7kip7sa8jmh98a3lge1u005gdct.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp5p6-bLErHScXLMCl2bmYQrxRq3ihdn4',
    appId: '1:369044560836:ios:87622413a71a2a9e7a2291',
    messagingSenderId: '369044560836',
    projectId: 'complete-e-commerce',
    storageBucket: 'complete-e-commerce.appspot.com',
    iosClientId: '369044560836-9dtoj7kip7sa8jmh98a3lge1u005gdct.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboard',
  );
}
